add filename to exec-file
mozilla/sops pull request #761
Opened 2020-10-23 13:52 UTC by cgroschupp

2020-12-29 08:33 UTC, cgroschupp commented
@ajvb @autrilla can you please review?

2020-12-29 08:35 UTC, autrilla commented
Before we add a new feature that we'll have to maintain forever, can you explain why this is useful for you? The file name gets passed to the command anyway, and there's no way for the command to know what it'll be ahead of time because the directory will have a random name.

2020-12-29 08:37 UTC, cgroschupp commented
@autrilla I have updated the description.

2020-12-29 08:47 UTC, autrilla requested changes
I'm OK with adding the feature, but other than my code comment, can you please:

1. Document this in README.md (similar to how e.g. `--user` is documented).
2. Modify the description with a more concrete example of a tool (actual commands, terraform works for me) that needs this to work properly? It would be useful for other people searching for a solution when they encounter the same problem you did.

2020-12-29 08:47 UTC, autrilla commented on cmd/sops/main.go
> +				}
This is broken, since you're not using `filename` again

2020-12-29 09:58 UTC, autrilla approved these changes
Thanks! We have some CI issues, but I'll make sure this PR will make it into the next release.

2021-02-08 14:24 UTC, renannprado commented
Looking forward to use this feature :smile:

2021-02-08 19:53 UTC, autrilla commented
Can you please rebase so this branch picks up the CI fixed that are now in develop?

2021-02-09 07:20 UTC, cgroschupp commented
@autrilla done

2021-02-09 12:11 UTC, autrilla commented
Thanks!

2021-02-09 12:11 UTC, merged